# Generated by Django 4.2.4 on 2024-04-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_lessons_course_lessons_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='course',
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
