# Generated by Django 4.2.4 on 2024-04-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_lessons_course_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
