# Generated by Django 4.2.4 on 2024-04-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_comment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='lesson',
        ),
    ]
