# Generated by Django 4.2.4 on 2024-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
    ]
