# Generated by Django 4.2.4 on 2024-04-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_course_comment_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='comment',
        ),
    ]
