# Generated by Django 4.2.4 on 2024-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course', '0007_rename_title_comment_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='UserType',
        ),
    ]
