# Generated by Django 4.2.4 on 2024-04-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('course', '0008_rename_customuser_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserType',
            new_name='CustomUser',
        ),
    ]
