# Generated by Django 4.2.4 on 2024-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_usertype_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=1, upload_to='users_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
